project:
  type: website
  output-dir: docs
website:
  title: "CEPE-Fundar "
  navbar:
    logo: " "
    left:
      - href: index.qmd
        text: "  "
    right:
      - href: encuesta.qmd
        text: "Investigación"
      - icon: github
        href: https://github.com/cepe-fundar
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



