project:
  type: website

website:
  title: " "
  navbar:
    logo: "images/loguito.png"
    left:
      - href: index.qmd
        text: "  "
      - href: about.qmd
        text: Sobre el hub
    right:
      - icon: github
        href: https://github.com/Nodo-IA

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



