project:
  type: website
  output-dir: docs
website:
  title: "CEPE-Fundar"
  navbar:
    background: "#7DA5C7"
    logo: " "
    left:
      - href: index.qmd
        text: "Nosotros"
      - href: encuesta.qmd
        text: "Investigación"  
    right:
      - icon: github
        href: https://github.com/cepe-fundar
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



